#!/usr/bin/env node
// Expand the unit icon set (prototypes/unit-icons/icons.js, the user's file,
// kept verbatim) into plain SVG documents and write them as a C++ header the
// game rasterises with nanosvg (src/Sect/unit_icons.cpp).
//
// The icons are JS templates (loops over wheel positions, rotated panels), so
// running the JS is the only faithful way to get their final markup. Colours:
// "currentColor" (ink) -> black, "var(--paper)" (knockout) -> white, over a
// white ground; the rasteriser then reads ink as 1 - luminance.
//
//   node tools/unit_icons/gen_unit_icons.js      (rewrites src/Sect/unit_icons_svg.h)
const fs = require('fs'), path = require('path');
const root = path.resolve(__dirname, '../..');
const { ICONS } = require(path.join(root, 'prototypes/unit-icons/icons.js'));
let out = `// GENERATED by tools/unit_icons/gen_unit_icons.js from prototypes/unit-icons/icons.js.
// Do not edit: change the JS and regenerate.
#ifndef UNIT_ICONS_SVG_H
#define UNIT_ICONS_SVG_H

struct UnitIconSvg
{
    const char* name;
    const char* svg;
};

static const UnitIconSvg UNIT_ICON_SVGS[] = {
`;
for (const [name, body] of Object.entries(ICONS)) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100">`
    + `<rect x="0" y="0" width="100" height="100" fill="#ffffff"/>`
    + body.replace(/currentColor/g, '#000000').replace(/var\(--paper\)/g, '#ffffff')
    + `</svg>`;
  out += `    {"${name}", R"SVG(${svg.replace(/\s+/g, ' ')})SVG"},\n`;
}
out += `};

#endif // UNIT_ICONS_SVG_H
`;
fs.writeFileSync(path.join(root, 'src/Sect/unit_icons_svg.h'), out);
console.log('wrote src/Sect/unit_icons_svg.h:', Object.keys(ICONS).join(', '));
