name: Windows

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'CMakeLists.txt'
      - '.github/workflows/windows.yml'
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write       # for actions/upload-release-asset to upload release asset
    runs-on: windows-latest

    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      PROJECT_RELEASE_PATH: ${{ github.event.repository.name }}_dev_win_x64

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4

    - name: Setup Release Paths
      run: |
        echo "PROJECT_RELEASE_PATH=${{ env.PROJECT_NAME }}_v${{ github.event.release.tag_name }}_win_x64" >> $GITHUB_ENV
      shell: bash
      if: github.event_name == 'release' && github.event.action == 'published'

    - name: Configure with CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Generate Artifacts
      run: |
        mkdir ${{ env.PROJECT_RELEASE_PATH }}
        copy build\src\Release\colony_game.exe ${{ env.PROJECT_RELEASE_PATH }}\colony_game.exe
        if exist src\assets xcopy src\assets ${{ env.PROJECT_RELEASE_PATH }}\assets /s /e /i
        copy README.md ${{ env.PROJECT_RELEASE_PATH }}\README.md
        copy LICENSE ${{ env.PROJECT_RELEASE_PATH }}\LICENSE
        dir ${{ env.PROJECT_RELEASE_PATH }}
        7z a .\${{ env.PROJECT_RELEASE_PATH }}.zip .\${{ env.PROJECT_RELEASE_PATH }}
      shell: cmd

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_RELEASE_PATH }}.zip
        path: ./${{ env.PROJECT_RELEASE_PATH }}.zip

    - name: Upload Artifact to Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.PROJECT_RELEASE_PATH }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'release' && github.event.action == 'published'
